// @flow
export const actionTypes = {
  UPDATE_REQUESTED: 'UPDATE_REQUESTED',
  UPDATE_FULFILLED: 'UPDATE_FULFILLED',
  UPDATE_REJECTED: 'UPDATE_REJECTED',

  REMOVE_REQUESTED: 'REMOVE_REQUESTED',
  REMOVE_FULFILLED: 'REMOVE_FULFILLED',
  REMOVE_REJECTED: 'REMOVE_REJECTED',

  LISTEN_REQUESTED: 'LISTEN_REQUESTED',
  LISTEN_FULFILLED: 'LISTEN_FULFILLED',
  LISTEN_REJECTED: 'LISTEN_REJECTED',
  LISTEN_CHILD_ADDED: 'LISTEN_CHILD_ADDED',
  LISTEN_CHILD_CHANGED: 'LISTEN_CHILD_CHANGED',
  LISTEN_CHILD_REMOVED: 'LISTEN_CHILD_REMOVED',
  LISTEN_REMOVED: 'LISTEN_REMOVED',

  REMOVE_LISTENER_REQUESTED: 'REMOVE_LISTENER_REQUESTED',
  REMOVE_ALL_LISTENERS_REQUESTED: 'REMOVE_ALL_LISTENERS_REQUESTED',

  GET_FLOCK_REQUESTED: 'GET_FLOCK_REQUESTED',
  GET_FLOCK_FULFILLED: 'GET_FLOCK_FULFILLED',
  GET_FLOCK_REJECTED: 'GET_FLOCK_REJECTED',

  SET_INITIAL_URL: 'SET_INITIAL_URL',
  REMOVE_INITIAL_URL: 'REMOVE_INITIAL_URL',
};

export const metaTypes = {
  userSettings: 'userSettings',
  flocks: 'flocks',
  chickens: 'chickens',
  eggs: 'eggs',
};

export const eventTypes = {
  CHILD_ADDED: 'CHILD_ADDED',
  CHILD_REMOVED: 'CHILD_REMOVED',
  CHILD_CHANGED: 'CHILD_CHANGED',
};
