# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'cluckrapp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for cluckrapp
  pod 'Firebase/Core'

  target 'cluckrappTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'cluckrapp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for cluckrapp-tvOS

  target 'cluckrapp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
